name: Checks
on:
  push:
  pull_request:
jobs:
  scalafmt:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
          apps: sbt-launcher
      - run: ./bin/scalafmt --test
