name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  unit:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.10]
        os: [ubuntu-latest]
        java: [11, 8]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1
        with:
          jvm: ${{ matrix.java }}
          apps: sbt-launcher
      - run: sbt ci-test
        env:
          SCALA_VERSION: ${{ matrix.scala }}
