name: Launchers
on:
  push:
    branches:
      - main
      - server-bin
  pull_request:
jobs:
  generate-launchers:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.12, 2.12.13, 2.12.14, 2.13.4, 2.13.5, 2.13.6]
        os: [ubuntu-latest, windows-2016, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
          apps: sbt-launcher
      - run: cd native && ./mill -i "native[$SCALA_VERSION].copyToArtifacts" ../artifacts/
        shell: bash
        env:
          SCALA_VERSION: ${{ matrix.scala }}
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 1

  upload-launchers:
    needs: generate-launchers
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: coursier/setup-action@v1
      with:
        jvm: 8
    - uses: actions/download-artifact@v2
      with:
        name: launchers
        path: artifacts/
    - run: cd native && ./mill -i upload ../artifacts/
      env:
        UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
