name: Launchers
on:
  push:
    branches:
      - main
      - server-bin
  pull_request:
jobs:
  generate-launchers:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.12, 2.12.13, 2.12.14, 2.13.4, 2.13.5, 2.13.6]
        os: [ubuntu-latest, windows-2016, macos-latest]
        exclude:
          - scala: 2.12.12
            os: windows-2016
            # 2.12.12 is the Scala version used by sbt
            # As a consequence, its Scala JARs have different paths, which
            # seem to confuse some scalajs-bundler internal stuff.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
          apps: sbt-launcher
      - run: |
          cd native && \
          ./mill -i "native[$SCALA_VERSION].writeNativeImageScript" generate.sh && \
          ./generate.sh && \
          ./mill -i "native[$SCALA_VERSION].copyToArtifacts" ../artifacts/
        if: runner.os != 'Windows'
        env:
          SCALA_VERSION: ${{ matrix.scala }}
      - run: |
          cd native
          @call ./mill.bat -i "native[%SCALA_VERSION%].writeNativeImageScript" generate.bat
          @call generate.bat
          @call ./mill.bat -i "native[%SCALA_VERSION%].copyToArtifacts" ../artifacts/
        shell: cmd
        if: runner.os == 'Windows'
        env:
          SCALA_VERSION: ${{ matrix.scala }}
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: launcher-${{ matrix.scala }}-${{ matrix.os }}
          path: artifacts/
          if-no-files-found: error
          retention-days: 1
      - run: cd native && ./mill -i upload ../artifacts/
        if: github.event_name == 'push'
        env:
          UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
