name: Launchers
on:
  push:
    branches:
      - main
      - server-bin
  pull_request:
jobs:
  unit:
    name: Launchers
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.14, 2.13.6]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
          apps: sbt-launcher
      - run: sbt ++$SCALA_VERSION server-cli/copyNativeImage
        if: runner.os != 'Windows'
        env:
          SCALA_VERSION: ${{ matrix.scala }}
      - run: sbt.bat ++%SCALA_VERSION% server-cli/copyNativeImage
        if: runner.os == 'Windows'
        env:
          SCALA_VERSION: ${{ matrix.scala }}
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2
